### ISSUE TITLE
Disalignment between DVS image and 3D annotation

### ISSUE THREAD

**Issue by kyang-06** [SensorsINI/DHP19#11]
Hi, thank you for great effort to build DHP dataset.
I met disalignment issue when visualizing the data.

![dvs](https://user-images.githubusercontent.com/16101166/90646893-4b8a7f80-e26a-11ea-9a5d-0040eb45f3f5.png)
As shown in the picture, the 2d keypoints projected from 3d gt label disalign with the DVS image. In this case, the label drifts a bit right for figure 1, and drifts left for figure 2. I'm sure it's not the problem about the visualization tools, since official jupyter script encounters this issue as well.
Could you tell me what cause this phenomenon?

**Comment by enrico-c** [comment]
Hi @ky66111 ,

I think what you're observing could be due to these two reasons:

The first is that we approximated the joint positions with the marker positions, and the marker positions are not exactly centered on the actual joints.

The second is that we calculated the projection matrices from the same set of frames for the 4 cameras. So the items we labeled were in the field of view of all the cameras and were not covering the whole camera space. This is the case in particular for the two lateral views, for which the projection matrices have lower quality.

**Comment by kyang-06** [comment]
Apologies for my late reply.
Many thanks to your exhaustive explanation!

**Comment by pengyuwang35** [comment]
> Hi, thank you for great effort to build DHP dataset.
> I met disalignment issue when visualizing the data.
> 
> ![dvs](https://user-images.githubusercontent.com/16101166/90646893-4b8a7f80-e26a-11ea-9a5d-0040eb45f3f5.png)
> As shown in the picture, the 2d keypoints projected from 3d gt label disalign with the DVS image. In this case, the label drifts a bit right for figure 1, and drifts left for figure 2. I'm sure it's not the problem about the visualization tools, since official jupyter script encounters this issue as well.
> Could you tell me what cause this phenomenon?

Hi，
Is the visualization done by processing H5 files? Could you please share your visualization method or code? Thank you
