### ISSUE TITLE
Issue with importAedet function

### ISSUE THREAD

**Issue by gianscarpe** [SensorsINI/DHP19#8]
Good morning, I'm trying to generate the dataset starting from raw data using the script `Generate_DHP19.m`. However, I'm getting the following error at `25 /home/rslsync/Resilio Sync/DHP19/DVS_movies/S11/session4/mov5.aedat`. It's the only file that generate this error. I'm not sure about what the error relates to, have you ever head a similar problem?

Matlab version R2019B
```
25 /home/rslsync/Resilio Sync/DHP19/DVS_movies/S11/session4/mov5.aedat
File format: 2.1
The logical indices contain a true value outside of the array bounds.

Error in ImportAedatDataVersion1or2 (line 323)
        output.data.polarity.timeStamp = allTs(polarityLogical);

Error in ImportAedat (line 232)
	output = ImportAedatDataVersion1or2(info);

Error in Generate_DHP19 (line 147)
                aedat = ImportAedat([movementsPath '/'], strcat(movString, '.aedat'));
```

**Comment by tobidelbruck** [comment]
can you play this file with jAERViewer?

When I play it (using Davis346blue AEChip) I see occasional warnings like
10:37:40 WARNING: net.sf.jaer.graphics.DavisRenderer.getIndex: Event 
ApsDvsEvent timestamp=68185254 address=1283457026 x=345 y=306 
special=false filteredOut=false type=0 polarity=Off, adcSample=0, 
readoutType=DVS out of bounds and cannot be rendered in bounds sizeX=346 
sizeY=260
  delaying next warning for 1000ms

It means that there are a few events with corrupted addresses. This 
probably was the result of errors in USB data transfer over the long USB 
cables.

You might add a check to the matlab reader to filter out addresses 
outside the 346x260 address space.


|25 /home/rslsync/Resilio Sync/DHP19/DVS_movies/S11/session4/mov5.aedat|

**Comment by enrico-c** [comment]
Hi @gianscarpe , thank you for your question. 
No, I don't get this error when generating the dataset. I am using matlab 2018b, but I also tried installing matlab 2019b and in both cases I could generate the frames/labels related to subject 11, session 4, movement 5. Maybe there was an issue when downloading the aedat file? One possibility would be to try downloading the data again. Another one would be for us to send you these generated files.

The error could be due to a mismatch when indexing the `allTs` vector (e.g. as discussed here https://ch.mathworks.com/matlabcentral/answers/489534-the-logical-indices-contain-a-true-value-outside-of-the-array-bounds). When setting a breakpoint I see that `allTs` and `polarityLogical` sizes match. Could you make this check too and see what these sizes are?

**Comment by gianscarpe** [comment]
Hi @enrico-c, thanks for the kind response. I solved my issue as @tobidelbruck suggested. I manually modified the index when loading aedat file in matlab. `allTs` was of size`polarityLogical` +1, probably due to errors during dataset download, so I removed only the last index.
Thank you both!

Gianluca
